//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localisation() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CourseWork.Localisation", typeof(Localisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кліки.
        /// </summary>
        internal static string Clicks {
            get {
                return ResourceManager.GetString("Clicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помилка!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чи дійсно ви бажаєте вийти з меню гри?(а як же єноти?).
        /// </summary>
        internal static string ExitRequest {
            get {
                return ResourceManager.GetString("ExitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вихід.
        /// </summary>
        internal static string ExitTitle {
            get {
                return ResourceManager.GetString("ExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будь-ласка, виберіть режим гри!.
        /// </summary>
        internal static string LevelsRadioButtonCheked {
            get {
                return ResourceManager.GetString("LevelsRadioButtonCheked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Програш!.
        /// </summary>
        internal static string Loss {
            get {
                return ResourceManager.GetString("Loss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Довжина нікнейму не повинна бути більша 16!.
        /// </summary>
        internal static string NicknameLengthTextbox {
            get {
                return ResourceManager.GetString("NicknameLengthTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значення в текстбоксі з нікнеймом не введено!.
        /// </summary>
        internal static string NicknameTextbox {
            get {
                return ResourceManager.GetString("NicknameTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Єноту вже багато уваги!!!.
        /// </summary>
        internal static string RaccoonALotAttention {
            get {
                return ResourceManager.GetString("RaccoonALotAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Єноту достатньо уваги!!!.
        /// </summary>
        internal static string RaccoonEnoughAttention {
            get {
                return ResourceManager.GetString("RaccoonEnoughAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Єноту мало уваги!.
        /// </summary>
        internal static string RaccoonLittleAttention {
            get {
                return ResourceManager.GetString("RaccoonLittleAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Єноту треба більше уваги!!.
        /// </summary>
        internal static string RaccoonNeedsMoreAttention {
            get {
                return ResourceManager.GetString("RaccoonNeedsMoreAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слава Єнотам!!!.
        /// </summary>
        internal static string RaccoonsGlory {
            get {
                return ResourceManager.GetString("RaccoonsGlory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ганьба єнотам!(((.
        /// </summary>
        internal static string RaccoonsShame {
            get {
                return ResourceManager.GetString("RaccoonsShame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Складність гри.
        /// </summary>
        internal static string RatingGameComplexity {
            get {
                return ResourceManager.GetString("RatingGameComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кількість ходів.
        /// </summary>
        internal static string RatingMovesNumber {
            get {
                return ResourceManager.GetString("RatingMovesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нікнейм.
        /// </summary>
        internal static string RatingNickname {
            get {
                return ResourceManager.GetString("RatingNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рейтингу ще немає.
        /// </summary>
        internal static string RatingNone {
            get {
                return ResourceManager.GetString("RatingNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Час проходження.
        /// </summary>
        internal static string RatingPassingTime {
            get {
                return ResourceManager.GetString("RatingPassingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перемога чи програш.
        /// </summary>
        internal static string RatingWinOrLose {
            get {
                return ResourceManager.GetString("RatingWinOrLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чи дійсно ви бажаєте вийти з меню налаштувань?.
        /// </summary>
        internal static string SettingsExitRequest {
            get {
                return ResourceManager.GetString("SettingsExitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значення в текстбокс для часу введено не правильно!.
        /// </summary>
        internal static string TimeTextbox {
            get {
                return ResourceManager.GetString("TimeTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значення в текстбоксі для часу та на трекбарі не вибрані! Будь-ласка, здійсніть вибір..
        /// </summary>
        internal static string TimeTrackbarTextbox {
            get {
                return ResourceManager.GetString("TimeTrackbarTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Україна не може програти!.
        /// </summary>
        internal static string UkraineLost {
            get {
                return ResourceManager.GetString("UkraineLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Україна перемогла!.
        /// </summary>
        internal static string UkraineWon {
            get {
                return ResourceManager.GetString("UkraineWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перемога!.
        /// </summary>
        internal static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
    }
}
